### ISSUE TITLE
MK808 and Ubuntu 16.04 - kernel panic and boot loop

### ISSUE THREAD

**Issue by tosiara** [sgjava/ubuntu-mini#2]
Hi,
have you tried running MK808, 3.0.8 kernel and latest Ubuntu 16.04?

I have followed steps as usually, prepared a root filesystem, copied firmware and modules - but I get stacktrace immediately after boot and device stays in this boot loop
Maybe you have a working MK808 16.04 root filesystem prepared so I can test?
Thanks

**Comment by sgjava** [comment]
16.04 required a later kernel. You are stuck with 14.04 unless a newer kernel is released. I've seen people running it on 3.19, but it really requires 4.x.
