### ISSUE TITLE
hdmi output resolution rk3066

### ISSUE THREAD

**Issue by zrafa** [sgjava/ubuntu-mini#3]
Hi, I have this kind of criter:
https://www.cnx-software.com/wp-content/uploads/2013/02/B12_PCB_Top_640px.jpg
http://freaktab.com/filedata/fetch?id=430066&d=1445082759

And, for some usage, we need to connect it to a vga monitor (max monitor resolution 1024x768_60)
I have an adapter hdmi to vga. Unfortunately, the kernel 3.0.8 and modules runs Xorg with 1920x1080 resolution. xrandr does not report any other kind of possible resolution. We need 1024x768 (our monitor max resolution).
Do you know some way to change the output resolution?
The Xorg driver is fbturbo. I got the kernel and modules from your project.

**Comment by sgjava** [comment]
Yea, these are kind of frozen in time with the 3.0.8 kernel. Usually when you build the kernel you can select the resolution. Check out https://github.com/sgjava/ubuntu-mini#build-3036-galland-kernel-for-rk3066

nano config.galland

    Find CONFIG_BOX_FB and comment out CONFIG_BOX_FB_720P=y uncomment # CONFIG_BOX_FB_480P is not set and change to CONFIG_BOX_FB_480P=y for instance

I haven't messed with these guys in years. I moved on to ODROIDs, NanoPis, etc.
