### ISSUE TITLE
mod-fw.tar.gz ?

### ISSUE THREAD

**Issue by OverWorldD** [sgjava/ubuntu-mini#5]
Hi! In the flash kernel stage, where does mod-fw.tar.gz come from?
 In step 
`sudo tar -pzxf mod-fw.tar.gz -C /`

**Comment by tosiara** [comment]
It is inside the archive, for example https://github.com/sgjava/ubuntu-mini/blob/master/rk3066/picuntu-rc2.tar.gz

**Comment by OverWorldD** [comment]
Aaah, I didn't realize it was extracted into a folder ;) Well, anywhoo. Unfortunately couldnt make it work on my TV-box... :( It just does not boot past initramfs

**Comment by sgjava** [comment]
Check the compatibility matrix. MK808s with BT will not work. I was never able to get networking cranking.
