### ISSUE TITLE
Confused my instructions

### ISSUE THREAD

**Issue by robross0606** [sgjava/ubuntu-mini#7]
I'm feeling very stupid here, but I'm very confused by the instructions between the "Create Ubuntu root filesystem MK808" and "Flash kernel" instructions.  They are written almost as if you need to use two different SD cards.  At the end of the "Create Ubuntu root filesystem" section, you create a `linuxroot.tar.gz` archive.  Then, in the next section you're back to "Preparing an SD card" again.  Why are there two different SD cards (i.e. "sdb" vs "sdg") involved here?  The requirements don't mention needing two SD.  What am I missing?

**Comment by sgjava** [comment]
https://github.com/sgjava/ubuntu-mini#create-ubuntu-root-filesystem-mk808-mk802iv-etc uses a VirtualBox VM to create the root file system. You have to flash the device which has internal storage to boot off SD which has Ubuntu. It's been several years since I've done this.

**Comment by robross0606** [comment]
I finally figured out that the instructions are just a little _off_ in what they meant.  It is basically supposed to be the same SD card prepared in the first section, just patched with the lib modules (drivers) in the second section.  I'm up and running, though a little disappointing how little I can do stuck on an old 3.0.8 kernel.

**Comment by sgjava** [comment]
Submit a PR if you think it will help make a better readme.
